name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "!*"
  pull_request:

env:
  NODE_VERSION: "16"
  TURBO_REMOTE_ONLY: "true"
  TURBO_TEAM: "vercel"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm i -g pnpm@7.24.2
      - run: pnpm install
      - run: pnpm build
